<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Template.Domain\Template.Domain.csproj" />
    <ProjectReference Include="..\Template.Application\Template.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../../../contracts/documents/search-index.json"
                      LogicalName="Template.Documents.SearchIndex.v1.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="OpenIddict.Client.AspNetCore" />
    <PackageReference Include="OpenIddict.Client.DataProtection" />
    <PackageReference Include="OpenIddict.Client.SystemNetHttp" />
    <PackageReference Include="OpenIddict.Client.WebIntegration" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
  </ItemGroup>

</Project>
