<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Template.Api\Template.Api.csproj" />
    <ProjectReference Include="..\..\src\Template.Infrastructure\Template.Infrastructure.csproj" />
  </ItemGroup>
</Project>
